# pre-commit configuration.
# Install:
#   pip install pre-commit
#   pre-commit install

exclude: ^(bench/|patches/|bench\.sh$|build-bench-env\.sh$|graph_many\.py$|scripts/bencher\.dev\.py$)

repos:
  - repo: https://gitcode.com/gh_mirrors/pr/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
